# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movie Groovy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movie Groovy
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'
  pod 'LBTATools'

end
